import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)


def _build_html(order: dict) -> str:
    order_num = order.get("Order_Number", "N/A")
    status = order.get("Process_Status", "")
    risk = order.get("Risk_Level", "")
    score = order.get("Deviation_Score", 0)
    deviations = order.get("Deviations", [])
    root_cause = order.get("root_cause", "")
    recommendation = order.get("recommendation", "")

    dev_rows = "".join(
        f"<tr><td>{d.get('type','')}</td><td>{d.get('severity','')}</td><td>{d.get('detail','')}</td></tr>"
        for d in deviations
    )

    return f"""
    <html><body style="font-family:Arial,sans-serif;color:#222;">
    <h2 style="color:#b02828;">⚠ Process Compliance Alert — Order {order_num}</h2>
    <table style="border-collapse:collapse;margin-bottom:16px;">
      <tr><td style="padding:4px 12px 4px 0;font-weight:bold;">Status</td><td>{status}</td></tr>
      <tr><td style="padding:4px 12px 4px 0;font-weight:bold;">Risk Level</td><td>{risk}</td></tr>
      <tr><td style="padding:4px 12px 4px 0;font-weight:bold;">Deviation Score</td><td>{score}</td></tr>
    </table>
    {"<p><b>Root Cause:</b> " + root_cause + "</p>" if root_cause else ""}
    {"<p><b>Recommendation:</b> " + recommendation + "</p>" if recommendation else ""}
    <h3>Detected Deviations</h3>
    <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%;">
      <thead style="background:#f5f5f5;">
        <tr><th>Type</th><th>Severity</th><th>Detail</th></tr>
      </thead>
      <tbody>{dev_rows}</tbody>
    </table>
    <p style="color:#888;font-size:12px;margin-top:24px;">
      Generated by OFI Process Compliance Agent
    </p>
    </body></html>
    """


def send_alerts_for_blocked(orders: list[dict]) -> list[str]:
    """Send HTML alert emails for each BLOCKED or HIGH-risk order."""
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASS", "")
    from_email = os.getenv("ALERT_FROM_EMAIL", smtp_user)
    to_email = os.getenv("ALERT_TO_EMAIL", "")

    if not smtp_user or not smtp_pass or not to_email:
        logger.warning("Email alerts skipped — SMTP credentials not configured in .env")
        return []

    targets = [
        o for o in orders
        if o.get("Process_Status") == "BLOCKED" or o.get("Risk_Level") in ("CRITICAL", "HIGH")
    ]

    sent = []
    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)

            for order in targets:
                order_num = order.get("Order_Number", "N/A")
                msg = MIMEMultipart("alternative")
                msg["Subject"] = f"[PCA Alert] {order.get('Process_Status')} Order {order_num} — Risk: {order.get('Risk_Level')}"
                msg["From"] = from_email
                msg["To"] = to_email
                msg.attach(MIMEText(_build_html(order), "html"))

                server.sendmail(from_email, to_email, msg.as_string())
                sent.append(str(order_num))
                logger.info("Alert sent for order %s", order_num)

    except Exception as e:
        logger.error("Failed to send alert emails: %s", e)

    return sent
